### PR TITLE
Updated micropython and edited modradio for latest MP version

### PR DESCRIPTION
**Pull request by hackgnar**
In order to make radiobit work with the latest microbits, I updated the version of MP to the newest upstream.  I also had to edit modradio a bit to make it work with the newest version.

I also updated the precompiled radiobit firmware with this code change.  Tested and verified working on my end.

Thanks for the great project Damien!  I've been having fun with it!

### CODE REVIEW

**Comment by hackgnar** [comment]
@virtualabs I had to make some edits to modradio to make it work with the latest version of MP.  Nothing too crazy, just some imports and the rest was simple with vimdiff.  The only hacky thing I did was change:

`timestamp` = uBit.systemTime();`

to

`timestamp = 0;`

because I wasn't sure what systemTime got changed to in the latest version of MP.

**Review by virtualabs — COMMENTED** [review]
First, thank you for this PR ! That's cool to see people contributing to this project. There is one or two details I want to discuss, no offense, it is just to make things clear. 

In this pull request, you removed some comments in the modradio.cpp file that stated my code borrowed some code to Bastille's Mousejack project (line 4 and 5). IMHO this comment must stay in Radiobit, as this module definitely uses some code borrowed from Mousejack, and I don't want them to argue because my code does not mention it. Moreover, I am no longer credited  as a contributor for this modradio module, and this bothers me as I spent countless hours to make it work. By the way, feel free to add your name or handle to the documentation, as you contributed to this project :) !

Does this version work with older microbits as well, or is it only designed to work with newer microbits ?

Anyway, thanks again for your contribution, I'm going to do some additional tests but it should work as expected I guess ;). I don't know if you can edit your pull-request to fix the few points I mentionned above, hope it would not be a pain in the bottom to do so.

**Comment by hackgnar** [comment]
I merged the old radiobit modradio headers back into the new version.  Good catch!

As for "Does this version work with older microbits".  To be honest, I have no idea.  If I had one, I would have used that instead of updating micropython for radiobit 😁.  

We could always revert the patch if it causes issues for older radiobits.

**Comment by virtualabs** [comment]
Well, we'll see. PR accepted and now merged. And yep, it is always possible to revert so no big deal. 

Thank you again for your contribution !

**Pull request merged**
